import type { NavigationTree } from '@/@types/navigation';
import { IconDashboard, IconUser } from '@tabler/icons-react';

const navigationConfig: NavigationTree[] = [
  {
    key: 'dashboard',
    path: '/dashboard',
    title: 'Library',
    translateKey: '',
    icon: IconDashboard,
    authority: [],
    subMenu: [],
  },
  {
    key: 'users',
    path: '/users',
    title: 'Calendar',
    translateKey: '',
    icon: IconUser,
    authority: [],
    subMenu: [],
  },
  {
    key: 'users',
    path: '/users',
    title: 'Activity',
    translateKey: '',
    icon: IconUser,
    authority: [],
    subMenu: [
      {
        key: 'users',
        path: '/users',
        title: 'Queue',
        translateKey: '',
        authority: [],
      },
      {
        key: 'users',
        path: '/users',
        title: 'History',
        translateKey: '',
        authority: [],
      },
      {
        key: 'users',
        path: '/users',
        title: 'Blocklist',
        translateKey: '',
        authority: [],
      },
    ],
  },
  {
    key: 'users',
    path: '/users',
    title: 'Wanted',
    translateKey: '',
    icon: IconUser,
    authority: [],
    subMenu: [],
  },
  {
    key: 'users',
    path: '/users',
    title: 'Settings',
    translateKey: '',
    icon: IconUser,
    authority: [],
    subMenu: [
      {
        key: 'users',
        path: '/users',
        title: 'Media Management',
        translateKey: '',
        authority: [],
      },
      {
        key: 'users',
        path: '/users',
        title: 'Profiles',
        translateKey: '',
        authority: [],
      },
      {
        key: 'users',
        path: '/users',
        title: 'Custom Formats',
        translateKey: '',
        authority: [],
      },
      {
        key: 'users',
        path: '/users',
        title: 'Indexers',
        translateKey: '',
        authority: [],
      },
      {
        key: 'users',
        path: '/users',
        title: 'Download Clients',
        translateKey: '',
        authority: [],
      },
      {
        key: 'users',
        path: '/users',
        title: 'Metadata Sources',
        translateKey: '',
        authority: [],
      },
      {
        key: 'users',
        path: '/users',
        title: 'General',
        translateKey: '',
        authority: [],
      },
      {
        key: 'users',
        path: '/users',
        title: 'Plugins',
        translateKey: '',
        authority: [],
      },
    ],
  },
  {
    key: 'users',
    path: '/users',
    title: 'System',
    translateKey: '',
    icon: IconUser,
    authority: [],
    subMenu: [
      {
        key: 'users',
        path: '/users',
        title: 'Status',
        translateKey: '',
        authority: [],
      },
      {
        key: 'users',
        path: '/users',
        title: 'Tasks',
        translateKey: '',
        authority: [],
      },
      {
        key: 'users',
        path: '/users',
        title: 'Events',
        translateKey: '',
        authority: [],
      },
      {
        key: 'users',
        path: '/users',
        title: 'Log Files',
        translateKey: '',
        authority: [],
      },
    ],
  },
];

export default navigationConfig;
